FROM alpine:edge

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    npm

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \ 
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

ENV TEST_HOME=/cucumber
ENV TEST_OUTPUT=$TEST_HOME/test-output

WORKDIR $TEST_HOME
RUN mkdir -p $TEST_OUTPUT

COPY package*.json ./
RUN npm install

COPY generate-cucumber-html.js ./
COPY features $TEST_HOME/features

#CMD ["./node_modules/.bin/cucumber-js", "-f", "json:cucumber.json node ; generate-cucumber-html.js"]
CMD ./node_modules/.bin/cucumber-js -f json:cucumber.json; node generate-cucumber-html.js